#pragma once
#include "stm32_conf.h"

#define PIN_USART_TX    {GPIOB, {GPIO_PIN_10, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_USART_RX    {GPIOB, {GPIO_PIN_11, GPIO_MODE_AF_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}

#define PIN_STEP_1      {GPIOA, {GPIO_PIN_0, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_2      {GPIOA, {GPIO_PIN_1, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_3      {GPIOA, {GPIO_PIN_2, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_4      {GPIOA, {GPIO_PIN_3, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_5      {GPIOA, {GPIO_PIN_4, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_6      {GPIOA, {GPIO_PIN_5, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_7      {GPIOA, {GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_8      {GPIOA, {GPIO_PIN_8, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_9      {GPIOA, {GPIO_PIN_9, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_STEP_10     {GPIOA, {GPIO_PIN_10, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}

const gpio_cfg_t tx = PIN_USART_TX;
const gpio_cfg_t rx = PIN_USART_RX;

const usart_cfg_t usart_cfg = {USART3, &tx, &rx, 115200, 10};

const load_cfg_t load_cfg = 
{
    {
        PIN_STEP_1, PIN_STEP_2, PIN_STEP_3, PIN_STEP_4, PIN_STEP_5,
        PIN_STEP_6, PIN_STEP_7, PIN_STEP_8, PIN_STEP_9, PIN_STEP_10
    }
};