#pragma once
#include "stm32_conf.h"

#define PIN_USART_TX    {GPIOB, {GPIO_PIN_10, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
#define PIN_USART_RX    {GPIOB, {GPIO_PIN_11, GPIO_MODE_AF_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH}}
